import AppKit
import CryptoKit
import Foundation

/// Polls `NSPasteboard.general.changeCount` — the only supported way to detect a
/// copy, since NSPasteboard has no change notification — and turns each new
/// change into a persisted `Clip`. The sole writer of new clips.
@MainActor
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private let clipStore: ClipStore
    private let preferences: Preferences

    private var timer: Timer?
    private var purgeTimer: Timer?
    private var lastChangeCount: Int

    /// Set by `Paster` right after it writes to the pasteboard so that change is
    /// recognized as our own paste, not a new copy, and skipped.
    var ownWriteChangeCount: Int?

    /// Called after a purge sweep actually removes an expired concealed clip, so
    /// the window can refresh its list if it's currently open.
    var onPurge: (() -> Void)?

    private static let transientTypes: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType")
    ]
    private static let concealedExpiry: TimeInterval = 60
    private static let purgeInterval: TimeInterval = 5

    init(clipStore: ClipStore, preferences: Preferences) {
        self.clipStore = clipStore
        self.preferences = preferences
        self.lastChangeCount = pasteboard.changeCount
    }

    /// Restarts the polling timer, picking up the current `preferences.pollInterval`
    /// — call again after changing it in Settings.
    func start() {
        stop()
        let timer = Timer(timeInterval: preferences.pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.checkForChange() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer

        let purgeTimer = Timer(timeInterval: Self.purgeInterval, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.purgeExpiredConcealedClips() }
        }
        RunLoop.main.add(purgeTimer, forMode: .common)
        self.purgeTimer = purgeTimer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        purgeTimer?.invalidate()
        purgeTimer = nil
    }

    private func purgeExpiredConcealedClips() {
        guard let removedSomething = try? clipStore.purgeExpired(), removedSomething else { return }
        onPurge?()
    }

    private func checkForChange() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count

        if let ownWriteChangeCount, count == ownWriteChangeCount {
            self.ownWriteChangeCount = nil
            return
        }

        guard let types = pasteboard.types, !types.isEmpty else { return }
        guard Set(types).isDisjoint(with: Self.transientTypes) else { return }

        let sourceApp = NSWorkspace.shared.frontmostApplication
        let sourceBundleID = sourceApp?.bundleIdentifier
        if let sourceBundleID, preferences.ignoredBundleIDs.contains(sourceBundleID) {
            return
        }

        guard let payload = try? buildPayload(
            types: types,
            sourceBundleID: sourceBundleID,
            sourceAppName: sourceApp?.localizedName
        ) else { return }

        do {
            try clipStore.insert(payload, historyLimit: preferences.historyLimit)
        } catch {
            NSLog("CmdV: failed to store clip: \(error)")
        }
    }

    private func buildPayload(
        types: [NSPasteboard.PasteboardType],
        sourceBundleID: String?,
        sourceAppName: String?
    ) throws -> ClipPayload? {
        let sourceURL = pasteboard.string(forType: NSPasteboard.PasteboardType("org.chromium.source-url"))
        let isConcealed = ConcealedDetector.isConcealed(types: types, sourceBundleID: sourceBundleID, sourceURL: sourceURL)
        let expiresAt = isConcealed ? Date().addingTimeInterval(Self.concealedExpiry) : nil

        if let imageData = imageData(from: types) {
            let saved = try ImageStore.saveImage(data: imageData, clipID: UUID().uuidString)
            return ClipPayload(
                kind: .image,
                previewText: "Image, \(saved.pixelWidth)\u{00D7}\(saved.pixelHeight)",
                imagePath: saved.imagePath,
                thumbPath: saved.thumbPath,
                pixelWidth: saved.pixelWidth,
                pixelHeight: saved.pixelHeight,
                byteSize: saved.byteSize,
                sourceBundleID: sourceBundleID,
                sourceAppName: sourceAppName,
                isConcealed: isConcealed,
                expiresAt: expiresAt,
                contentHash: Self.hash(imageData)
            )
        }

        if types.contains(.fileURL), let urlStrings = pasteboard.propertyList(forType: .fileURL) as? [String] {
            let joined = urlStrings.joined(separator: "\n")
            return ClipPayload(
                kind: .fileURL,
                plainText: joined,
                previewText: String(joined.prefix(500)),
                sourceBundleID: sourceBundleID,
                sourceAppName: sourceAppName,
                isConcealed: isConcealed,
                expiresAt: expiresAt,
                contentHash: Self.hash(Data(joined.utf8))
            )
        }

        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            let clipID = UUID().uuidString
            var payloadPath: String?
            let richRepresentations = Self.repairOrphanedListMarkup(
                in: representations(for: types, excluding: [.string]),
                plainText: string
            )
            if !richRepresentations.isEmpty {
                payloadPath = try ImageStore.savePayload(richRepresentations, clipID: clipID)
            }
            return ClipPayload(
                kind: .text,
                plainText: string,
                previewText: String(string.prefix(500)),
                payloadPath: payloadPath,
                sourceBundleID: sourceBundleID,
                sourceAppName: sourceAppName,
                isConcealed: isConcealed,
                expiresAt: expiresAt,
                contentHash: Self.hash(Data(string.utf8))
            )
        }

        return nil
    }

    private func imageData(from types: [NSPasteboard.PasteboardType]) -> Data? {
        for type: NSPasteboard.PasteboardType in [.png, .tiff] {
            if types.contains(type), let data = pasteboard.data(forType: type) {
                return data
            }
        }
        return nil
    }

    private func representations(
        for types: [NSPasteboard.PasteboardType],
        excluding: Set<NSPasteboard.PasteboardType>
    ) -> [String: Data] {
        var result: [String: Data] = [:]
        for type in types where !excluding.contains(type) {
            if let data = pasteboard.data(forType: type) {
                result[type.rawValue] = data
            }
        }
        return result
    }

    /// Chrome (and some other browsers) will copy a selection of list items as
    /// bare `<li>` fragments with no wrapping `<ol>`/`<ul>` when the selection
    /// boundary lands inside the list rather than around it — the list markup
    /// is simply incomplete on the source's own pasteboard write, before CmdV
    /// ever sees it. An app pasting that HTML has no structural signal that
    /// these `<li>`s form one list, so it falls back to a generic bullet guess
    /// instead of a real native list. Wrapping the orphaned fragment in the
    /// right list tag (inferred from whether the plain-text sibling looks
    /// numbered) restores what the source should have produced.
    private static func repairOrphanedListMarkup(in representations: [String: Data], plainText: String) -> [String: Data] {
        var result = representations
        for type in ["public.html", "Apple HTML pasteboard type"] {
            guard let data = result[type], let html = String(data: data, encoding: .utf8) else { continue }
            let lower = html.lowercased()
            guard lower.contains("<li"), !lower.contains("<ol"), !lower.contains("<ul") else { continue }
            let tag = looksLikeOrderedList(plainText) ? "ol" : "ul"
            result[type] = Data("<\(tag)>\(html)</\(tag)>".utf8)
        }
        return result
    }

    private static func looksLikeOrderedList(_ text: String) -> Bool {
        let lines = text.split(separator: "\n").map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
        guard !lines.isEmpty else { return false }
        return lines.allSatisfy { line in
            guard let markerEnd = line.firstIndex(where: { $0 == "." || $0 == ")" }) else { return false }
            let prefix = line[line.startIndex..<markerEnd]
            return !prefix.isEmpty && prefix.allSatisfy(\.isNumber)
        }
    }

    private static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).compactMap { String(format: "%02x", $0) }.joined()
    }
}
